language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 8723150/docker-react -f Dockerfile.dev .

script:
  - docker run 8723150/docker-react npm run test -- --coverage
